// Export all schemas
export * from './clients';
export * from './leads';
export * from './conversations';
export * from './scheduled-messages';
export * from './appointments';
export * from './invoices';
export * from './blocked-numbers';
export * from './error-log';
export * from './webhook-log';
export * from './message-templates';
export * from './daily-stats';
export * from './active-calls';
export * from './team-members';
export * from './escalation-claims';
export * from './business-hours';
export * from './call-attempts';
export * from './ab-tests';
export * from './reports';
export * from './template-variants';
export * from './template-performance-metrics';
export * from './api-usage';
export * from './api-usage-daily';
export * from './api-usage-monthly';
export * from './usage-alerts';
export * from './magic-link-tokens';
export * from './flow-enums';
export * from './flow-templates';
export * from './flows';
export * from './flow-executions';
export * from './template-metrics-daily';
export * from './template-step-metrics';
export * from './client-flow-outcomes';
export * from './knowledge-base';
export * from './notification-preferences';

// Auth tables (NextAuth)
export * from './auth';

// Export all relations for type-safe queries
export * from './relations';
